{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "name" : "categories",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "requests.exceptions.SSLError: HTTPSConnectionPool(host='reqres.in', port=443): Max retries exceeded with url: /api/users?page=2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))",
      "children" : [ {
        "name" : "test_get_method",
        "uid" : "a734b4d9eb6ea725",
        "parentUid" : "33268aa9b7026ff71471f3213f450db1",
        "status" : "broken",
        "time" : {
          "start" : 1725904964203,
          "stop" : 1725904964365,
          "duration" : 162
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "33268aa9b7026ff71471f3213f450db1"
    }, {
      "name" : "requests.exceptions.SSLError: HTTPSConnectionPool(host='reqres.in', port=443): Max retries exceeded with url: /api/users (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))",
      "children" : [ {
        "name" : "test_post_method",
        "uid" : "763c95b1ccc69f05",
        "parentUid" : "89e6dd0363808e58ff1564293efd6cb3",
        "status" : "broken",
        "time" : {
          "start" : 1725904964530,
          "stop" : 1725904964600,
          "duration" : 70
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "89e6dd0363808e58ff1564293efd6cb3"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  } ]
}